# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Mengjun Liu (刘孟君)
description: >- # this means to ignore newlines until "baseurl:"
  Mengjun Liu's Homepage
baseurl: "" # the subpath of the site
url: "https://mengjunliu-source.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.JPG

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Publications

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: mliu62685@gmail.com
      link: mailto:mliu62685@gmail.com
  follow:
    - name: GitHub
      link: http://github.com/mjliu2020

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
